package main

//// This header is generated by glib-compile-resources in Makefile
// #cgo pkg-config: gio-2.0
// #include "resources.h"
import "C"

import (
	"os"

	"github.com/dawidd6/checksumo/src/controller"
	"github.com/dawidd6/checksumo/src/model"
	"github.com/dawidd6/checksumo/src/view"
)

// Those are set via -ldflags in Makefile
var (
	appName      string
	appID        string
	localeDomain string
	localeDir    string
	uiResource   string
)

func main() {
	m := model.New()
	v := view.New(appName, appID, localeDomain, localeDir, uiResource)
	c := controller.New(v, m)

	os.Exit(c.Run())
}
